baseURL: https://dacort.xyz/
languageCode: en-us
title: Damon Cortesi

theme: "PaperMod"

params:
  description: Data Infrastructure Engineer

  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowFullTextinRSS: true

  assets:
    favicon: /images/favicon.ico


  profileMode:
    enabled: true
    title: Hi there ðŸ‘‹
    subtitle: >
      My name is Damon and I'm a data infrastrucuture engineer.

      
      
      ðŸ’ I love building open source tools, spinning up clusters with hundreds of nodes, and spending time in the woods.
    imageUrl: "/images/dacort.jpeg" # optional
    imageTitle: "@dacort" # optional
    buttons:
      - name: Blog
        url: "/posts"
      - name: AWS Videos
        url: "https://www.youtube.com/c/dacort"

  homeInfoParams:
    Title: Hi there ðŸ‘‹
    Content: >
      My name is Damon and I'm a data infrastrucuture engineer.

      - I love building open source tools, spinning up clusters with hundreds of nodes, and spending time in the woods.

  socialIcons:
    - name: youtube
      url: "https://www.youtube.com/c/dacort"
    - name: github
      url: "https://github.com/dacort"
    - name: bluesky
      url: "https://bsky.app/profile/dacort.velocipig.com"

  cover:
    hiddenInList: true # hide on list pages and home

menu:
  main:
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: deep-thoughts
      name: Deep Thoughts
      url: /deep-thoughts-by-ai/
      weight: 15
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
