baseURL: https://dacort.dev/
languageCode: en-us
title: Damon Cortesi

theme: "PaperMod"

params:
  description: AWS Analytics Developer Advocate

  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowReadingTime: true
  ShowFullTextinRSS: true

  assets:
    favicon: /images/favicon.ico


  profileMode:
    enabled: true
    title: Hi there ðŸ‘‹
    subtitle: >
      My name is Damon and I'm a developer advocate for analytics at AWS.

      
      
      ðŸ’ I work primarily with EMR but also have fun on the side with Athena and anything data-related.
    imageUrl: "/images/dacort.jpeg" # optional
    imageTitle: "@dacort" # optional
    buttons:
      - name: Blog
        url: "/posts"
      - name: AWS Videos
        url: "https://youtube.com/channel/UCKtlXVZC2DqzayRlZYLObZw"
      - name: Demo Code
        url: "https://github.com/dacort/demo-code"

  homeInfoParams:
    Title: Hi there ðŸ‘‹
    Content: >
      My name is Damon and I'm a developer advocate for analytics at AWS.

      - I work primarily with EMR but also have fun on the side with Athena and anything data-related.

  socialIcons:
    - name: twitter
      url: "https://twitter.com/dacort"
    - name: youtube
      url: "https://youtube.com/channel/UCKtlXVZC2DqzayRlZYLObZw"
    - name: github
      url: "https://github.com/dacort"

  cover:
    hiddenInList: true # hide on list pages and home

menu:
  main:
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 10
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 20
